<a href="https://colab.research.google.com/github/KorotkovNikita/PDA_SOL/blob/main/%D0%9A%D0%BE%D0%BF%D0%B8%D1%8F_%D0%B1%D0%BB%D0%BE%D0%BA%D0%BD%D0%BE%D1%82%D0%B0_%22C%D0%A02_ipynb%22.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Выполнил Коротков Н.А.

1) Импортировать numpy и написать версию

In [ ]:
import numpy as np
np.version.full_version

'1.23.5'

2) Создать нулевой вектор размера 10

In [ ]:
vec=np.zeros(10)
print(vec)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


3) Создать вектор заполненный 7-ами размера 7

In [ ]:
vector = [7] * 7
print(vector)

[7, 7, 7, 7, 7, 7, 7]


4) Создать вектор заполненный четными числами от 10 до 100

In [ ]:
vector = [x for x in range(10, 101) if x % 2 == 0]
print(vector)

[10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100]


5) Создать массив случайных чисел и развернуть его задом наперёд

In [ ]:
import random
array = [random.randint(1, 100) for _ in range(10)]
print("Исходный массив:", array)
reversed_array = array[::-1]
print("Развёрнутый массив:", reversed_array)

Исходный массив: [60, 92, 46, 55, 35, 78, 51, 79, 27, 20]
Развёрнутый массив: [20, 27, 79, 51, 78, 35, 55, 46, 92, 60]


6) Создать двумерную матрицу размера 3 на 3, заполненную числами от 0 до 9

In [ ]:
matrix = [[j for j in range(10*i, 10*i+3)] for i in range(3)]
print(matrix)

[[0, 1, 2], [10, 11, 12], [20, 21, 22]]


7) Создать матрицу размера 4 на 4 с единицами на диагонали смещеной на один наверх.

In [ ]:
matrix = np.zeros((4, 4), dtype=int)
np.fill_diagonal(matrix[1:], 1)
print(matrix)

[[0 0 0 0]
 [1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]]


8) Создать матрицу с числами в диапазоне от 1 до 4 по диагонали. В других ячейках матрицы должны быть семерки.

In [ ]:
matrix = [[7 for _ in range(4)] for _ in range(4)]  # Создаем матрицу 4x4 заполненную семерками
for i in range(4):
    matrix[i][i] = i + 1  # Заполняем числами от 1 до 4 по диагонали
    # Выводим матрицу на экран
for row in matrix:
    print(row)

[1, 7, 7, 7]
[7, 2, 7, 7]
[7, 7, 3, 7]
[7, 7, 7, 4]


9) Создать матрицу размера 5 на 5 заполненную чилами от 0 до 4 в строках.

In [ ]:
matrix = np.zeros((5, 5), dtype=int)  # Создаем матрицу из нулей размером 5 на 5
for i in range(5):  # Проходим по каждой строке матрицы
    matrix[i] = np.arange(5)  # Заполняем текущую строку числами от 0 до 4
print(matrix)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


10) Создать матрицу случайных чисел размера 10 на 10 и отнять среднее по строкам из каждого элемента строки

In [ ]:
import numpy as np
matrix = np.random.rand(10, 10) # Создание матрицы размера 10 на 10 со случайными числами от 0 до 1
row_means = np.mean(matrix, axis=1) # Вычисление среднего по каждой строке
matrix -= row_means.reshape(-1, 1) # Вычитание среднего из каждого элемента строки
print(matrix)

[[-0.01190936 -0.34881684 -0.05100284  0.46763098 -0.25274252 -0.26564168
  -0.11325459 -0.04591974  0.29418606  0.32747053]
 [-0.13691643 -0.00257933 -0.05194303  0.36623422 -0.37332125 -0.18207894
  -0.19762146  0.45261049  0.06863396  0.05698178]
 [ 0.12399396 -0.13452048 -0.38222695  0.20064493 -0.29049958  0.23922128
   0.01509121 -0.14833479  0.26828468  0.10834577]
 [ 0.34835567  0.2608414  -0.48713946 -0.57594101  0.16480359  0.31867318
   0.18630647  0.20795119 -0.14470425 -0.27914679]
 [-0.03190382  0.43663197 -0.42176496 -0.41372829 -0.3369586  -0.35125745
   0.19375032  0.4380273   0.51664591 -0.02944237]
 [-0.22336943  0.45358475  0.00390797 -0.06092404  0.33834242 -0.03031221
  -0.33502198 -0.19078882  0.23730489 -0.19272355]
 [-0.3651303   0.10347994  0.02475439 -0.18350788 -0.33273815  0.25914797
   0.12849361  0.00302918  0.14949254  0.21297869]
 [ 0.27379682 -0.10592452  0.07026337  0.30625359  0.17612356 -0.18950861
   0.31421632 -0.42920143 -0.05939953 -0.35661957]


11) Создать матрицу случайных чисел размера 10 на 10 и отнять медиану по столбцам из каждого элемента столбца  

In [ ]:
import numpy as np
matrix = np.random.rand(10, 10) # Создание матрицы размера 10 на 10 со случайными числами от 0 до 1
column_medians = np.median(matrix, axis=0) # Вычисление медианы по столбцам
result_matrix = matrix - column_medians # Отнимаем медиану по столбцам из каждого элемента столбца
print(result_matrix)

[[ 0.04528132 -0.27596337 -0.01891944 -0.01748503  0.0147871   0.03078655
   0.09280839  0.02230612 -0.36749893 -0.39729714]
 [-0.31930842  0.10478013  0.53404187 -0.42843736  0.27445243 -0.10152327
  -0.39766719 -0.17672486  0.03660607 -0.51754552]
 [-0.14280678  0.17871031 -0.33368306 -0.39586415 -0.0147871  -0.40236298
  -0.33243964  0.5538067  -0.25513989  0.20242433]
 [ 0.39201426  0.29847084 -0.06037048  0.47017943 -0.0435498  -0.38474916
   0.37882122  0.35126082  0.14510199 -0.53116515]
 [-0.20726319 -0.14217954  0.2236175   0.01748503  0.30051433  0.34332999
  -0.09280839  0.12471836  0.2639099  -0.19080008]
 [-0.04528132  0.04183477  0.07423935  0.49826711  0.29259638  0.32846299
   0.20757051  0.6826794  -0.03660607  0.44312962]
 [-0.54312583 -0.43622504  0.43261837 -0.28468787  0.27971822 -0.34087616
   0.37889834 -0.16183506  0.12650331  0.40754588]
 [ 0.05233191  0.22210863  0.01891944 -0.32910884 -0.36140711  0.04789412
  -0.17236811 -0.02230612  0.48709137  0.19080008]


12) Создать матрицу случайных чисел 5x5. Добавить к ней столбецы максимумов и минимумов по строкам. Получится матрица 5x7.  

In [ ]:
import numpy as np
# Создание матрицы 5x5 случайных чисел
matrix = np.random.randint(0, 10, size=(5, 5))
# Добавление столбца максимумов по строкам
max_column = np.max(matrix, axis=1).reshape(-1, 1)
matrix_with_max_column = np.hstack((matrix, max_column))
# Добавление столбца минимумов по строкам
min_column = np.min(matrix, axis=1).reshape(-1, 1)
matrix_with_min_column = np.hstack((matrix_with_max_column, min_column))
print(matrix_with_min_column)

[[8 1 7 9 8 9 1]
 [9 6 8 0 1 9 0]
 [0 7 7 9 2 9 0]
 [7 4 7 3 7 7 3]
 [3 6 4 9 0 9 0]]


13) Вектор чисел от 1 до 51 преобразовать в вектор нечетных чисел и в вектор четных чисел, поменять их размерности, чтобы получились две матрица. Найти произведение этих матриц. Найти обратную матрицу эётого произведения.  

14) Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и единицами.

In [ ]:
matrix = np.zeros((8, 8), dtype=int)
for i in range(8):
    for j in range(8):
        if (i + j) % 2 == 0:
            matrix[i, j] = 1
print(matrix)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]
